export const GET_SEMI_FINISHED = 'GET_SEMI_FINISHED';
export const GET_ELABORATION = 'GET_ELABORATION';
export const GET_CATALOG = 'GET_CATALOG';
export const GET_STOCK = 'GET_STOCK';
export const GET_WORKERS = 'GET_WORKERS';